config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  get "search" => "searches#search_result"
  resources :books do
    resources :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end
  resources :users do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # class Follower フォロ-する側目線
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :follower_relationships, source: :followed

  # class Followed フォロ-される側目線
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed_relationships, source: :follower

    # model/user.rb
  # ユーザーをフォローする
  def follow(user_id)
   follower_relationships.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
   follower_relationships.find_by(followed_id: user_id).destroy
  end
  # フォロー確認をおこなう
  def following?(user)
   self.followings.include?(user)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
     @book = Book.find(params[:id])
     @book_comment = BookComment.new
     @user = @book.user
     @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @followers = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search_result
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%></td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger"%></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$(".comments").html("<%= j(render 'book_comments/book_comments', { book: @book }) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$(".comments").html("<%= j(render 'book_comments/book_comments', { book: @book }) %>")

app/views/books/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form middle">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/books/_userinfo.html.erb
  <div class="col-md-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no-image.jpeg"%>
    <table class="table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
      </tr>
      <tr>
        <% if current_user.id != user.id %>
          <% if current_user.following?(user) %>
            <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
          <% else %>
            <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
          <% end %>
        <% end %>
      </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    </div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= form_with model:@book, local:true do |f| %>
    		<div class="form-group">
    		  <label for="book_title">Title</label>
    		  <%= f.text_field :title, class: "form-control book_title" %>
    		</div>
    		<div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      <%= link_to "Back", books_path %>

  	</div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0" >
  <% if @book.errors.any? %>
  <div class="error" >
    <%= pluralize(@book.errors.count, "error") %>prohibited this obj from being saved
  </div>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li class="error" ><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="row">
    <%= render 'userinfo', user: @user, book: @book %>


    <div class="col-md-8 offset-md-1">
  		<h2>Books</h2>
  		<table class="table table-hover table-inverse">
  		  <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
    		 <% @books.each do |book| %>
    		  <tr>
    		    <td>
    		      <%= link_to user_path(book.user) do %>
    		      <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%><br/>
    		      <% end %>
    		    </td>
      			<td><%= link_to book.title, book_path(book) %></td>
      			<td><%= book.body %></td>
      			<!--#部分テンプレートにした箇所(部分的に更新したい箇所)-->
　        　<td id="favorite_buttons_<%= book.id %>">
　　        　<%= render "favorites/favorites", book: book %>
      			</td>
      			<td>コメント数: <%= book.book_comments.count %></td>
      		</tr>
      	<% end %>
        </tbody>
  		</table>
  	</div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no-image.jpeg"%>
      <table class="table">
        <tbody><tr></tr>
        <tr>
	        <th>name</th>
	        <th><%= @user.name %></th>
        </tr>
        <tr>
	        <th>introduction</th>
	      <th><%= @user.introduction %></th>
        </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to '', edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:@new_book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>


    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table table-hover table-inverse">
        <tbody>
    		  <tr>
    		    <td>
    		      <%= link_to user_path(@user) do %>
    		      <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%><br/>
    		      <%= @user.name %>
    		      <% end %>
    		    </td>
      			<td><%= link_to @book.title, book_path(@book) %></td>
      			<td><%= @book.body %></td>
      			<td><% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  ♥<%= @book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ♡<%= @book.favorites.count %>
                <% end %>
              </p>
            <% end %>
      			</td>
      			<td>コメント数: <%= @book.book_comments.count %></td>
      			<!--自分が投稿した本の編集・削除は見れて、他人の方の本の投稿は編集・削除が見れないようにする-->
      			<% if @book.user == current_user %>
      			<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
      			<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" %></td>
      			<% end %>
      		</tr>
      	</tbody>
  		</table>
    		<div class="comments">
　　      <%= render "book_comments/book_comments", book: @book %>
        </div>
      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
          <%= f.text_area :comment, size:"90×5" %>
          <h6><%= f.submit "送信" %></h6>
        <% end %>
      </div>
  	</div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
       ♡<%= book.favorites.count %>
     <% end %>
   </p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<table class="table table-hover table-inverse">
<% if @followers.exists? %>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= attachment_image_tag follower, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%></td>
        <td><%= follower.name %></td>
        <td>フォロー数: <%= follower.followings.count %></td>
        <td>フォロワー数: <%= follower.followers.count %></td>
        <td><%= link_to "Show", user_path(follower) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Following Users</h2>
<table class="table table-hover table-inverse">
<% if @users.exists? %>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/search_result.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
  <h2>User search for <%= @word %> </h2>
   <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
   </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
    	 <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%></td>
       <td><%= user.name %></td>
       <td><%= link_to "フォロー数: #{user.followings.count}", user_followings_path(user.id) %></td>
       <td><%= link_to "フォロワー数: #{user.followers.count}", user_followers_path(user.id) %></td>
       <td><% if current_user.id != user.id %>
             <% if current_user.following?(user) %>
             <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
              <% else %>
             <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
             <% end %>
          <% end %>
       </td>
       <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
  <h2>Book search for <%= @word %> </h2>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
    		      <%= link_to user_path(book.user) do %>
    		      <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%><br/>
    		      <% end %>
    		  </td>
          <td><%=link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <%= @user.errors.count %> errors prohibited this obj from being saved
  <ul>
    <% @user.errors.full_messages.each do |message| %>
  　<li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
      <h4><%= f.submit 'Update User', class: "btn btn-secondary" %></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/userinfo', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
  		<h2>Users</h2>
  		<table class="table table-hover table-inverse">
  		  <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
    		 <% @users.each do |user| %>
    		  <tr>
    		    <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%></td>
      			<td><%= user.name %></td>
      			<td><%= link_to "フォロー数: #{user.followings.count}", user_followings_path(user.id) %></td>
      			<td><%= link_to "フォロワー数: #{user.followers.count}", user_followers_path(user.id) %></td>
        		<td><% if current_user.id != user.id %>
                  <% if current_user.following?(user) %>
                    <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
                  <% else %>
                    <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
                  <% end %>
                <% end %></td>

      			<td><%= link_to "Show", user_path(user) %></td>
      		</tr>
      		<% end %>
      	</tbody>
  		</table>
  	</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
  <%= render 'books/userinfo', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
  		<h2>Books</h2>
  		<table class="table table-hover table-inverse">
  		  <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
    		 <% @books.each do |book| %>
    		  <tr>
    		    <td>
    		      <%= link_to user_path(book.user) do %>
    		      <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no-icon.jpeg"%><br/>
    		      <% end %>
    		    </td>
      			<td><%= link_to book.title, book_path(book) %></td>
      			<td><%= book.body %></td>
      		</tr>
      		<% end %>
      	</tbody>
  		</table>
  	</div>
  </div>
</div>